package com.hector.examenfinal.models.entity;
// Generated 2020 Feb 9 01:48:04 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.Valid;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotEmpty;

//Entidad Mail

/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name="mail"
    ,schema="public"
)
@SequenceGenerator(name="seqMail", initialValue=10, allocationSize=100)
public class Mail  implements java.io.Serializable {

	//Atributos
	
	 private static final long serialVersionUID = 1L;
	
	 private long id;
     private Usuario usuario;
     private String mail;

    //Constructores
     
    public Mail() {
    }

    public Mail(long id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Mail(long id, Usuario usuario, String mail) {
       this.id = id;
       this.usuario = usuario;
       this.mail = mail;
    }
   
    //Propiedades
    
    @Id 
  	@GeneratedValue(strategy = GenerationType.SEQUENCE , generator="seqMail")
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
   
    @Valid
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @NotEmpty(message="No puede estar vacío")
	@Email(message="No es una dirección de correo bien formada")
    @Column(name="mail")
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

}


