package com.hector.examenfinal.models.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

//ID de compra

/**
 * ProductosClientesId generated by hbm2java
 */
@Embeddable
public class ProductosClientesId  implements java.io.Serializable {

     //Atributos
	
	 private static final long serialVersionUID = 1L;
	 
	 private Long clienteId;
     private Long productoId;
     private Date fecha;

     //Constructores
     
    public ProductosClientesId() {
    }

    public ProductosClientesId(Long clienteId, Long productoId, Date fecha) {
       this.clienteId = clienteId;
       this.productoId = productoId;
       this.fecha = fecha;
    }
   
    //Propiedades

    @Column(name="cliente_id", nullable=false)
    public Long getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Long clienteId) {
        this.clienteId = clienteId;
    }


    @Column(name="producto_id", nullable=false)
    public Long getProductoId() {
        return this.productoId;
    }
    
    public void setProductoId(Long productoId) {
        this.productoId = productoId;
    }
    

    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductosClientesId) ) return false;
		 ProductosClientesId castOther = ( ProductosClientesId ) other; 
         
		 return (this.getClienteId()==castOther.getClienteId())
 && (this.getProductoId()==castOther.getProductoId())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = (int) (37 * result + this.getClienteId());
         result = (int) (37 * result + this.getProductoId());
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


